OOP版lsコマンドを作成
motohiro-mm/ruby-practices pull request #14
Opened 2023-12-12 12:14 UTC by motohiro-mm

2023-12-18 14:19 UTC, u1tnk requested changes
クラス構成から考えなおして欲しいので、ちょっと目についたところだけコメントしてます。

2023-12-18 14:19 UTC, u1tnk commented on 07.ls_object/lib/file_info.rb
> +  attr_reader :name, :stat
nameを外で使うのは分かりますが、 statは外から直接触れなくて良いですね。
statを使ってることをクラス外は知らなくて良いんです。
そうやって責務を分割していくのがオブジェクト指向で大事です。

2023-12-18 14:19 UTC, u1tnk commented on 07.ls_object/lib/ls_command.rb
> +  attr_reader :file_names
これは testで使っているようですが、testは出力されたものを見た方が良いですね。
内部データをテストするのはやることはありますがあんまり良くないです。
ちなみにどうしても内部データをテストしたいのであれば rubyでは無理やり触る方法はあるのでテストの為にメソッドを作ったりアクセス可能にすることはしなくて良いです。

2023-12-21 04:40 UTC, motohiro-mm commented on 07.ls_object/lib/file_info.rb
> +  attr_reader :name, :stat
> 責務を分割していくのがオブジェクト指向で大事です。

クラスを再構成して当初コメントを読んだ時よりも理解できたように思います。
ありがとうございます！

2023-12-21 04:40 UTC, motohiro-mm commented on 07.ls_object/lib/ls_command.rb
> +  attr_reader :file_names
> testは出力されたものを見た方が良いですね。
内部データをテストするのはやることはありますがあんまり良くないです。

なんでもかんでもtestしようとしてしまっていたのが良くなかったですね。
今後は出力されたものを確認するためにテストをつくるようにします。

2023-12-21 04:41 UTC, motohiro-mm commented
クラスを再構成して修正しました！
ご確認をお願いします。

2023-12-21 05:10 UTC, motohiro-mm commented
クラス構成を変更し修正しました。
ご確認をお願いいたします！

2023-12-22 15:38 UTC, u1tnk requested changes
色々コメントしたのでだいぶ方向性は分かったと思います。
だいぶ変更入ると思うので Formatの中身はあんまり見ていませんが、Formatからも別のクラスに移動して良い機能があると思うので考えてみてください 💪

2023-12-22 15:38 UTC, u1tnk commented on 07.ls_object/lib/ls_command.rb
> +    @directory_with_format = options['l'] ? FormatLong.new(pick_up_path_names(options, path)) : FormatShort.new(pick_up_path_names(options, path))
変数名は悪くは無いですが、後で使う方は 使い方だけ分かれば良いので、 FormatXXXの方の名前だけで良いですね。
また、前回指摘が漏れましたが。 FormatLongという名前はちょっと良くないです。
クラス名は名詞の方が良いので LongFormatterで 変数名も formatterが自然です。

2023-12-22 15:38 UTC, u1tnk commented on 07.ls_object/lib/ls_command.rb
> +  def ls_print(terminal_width)
クラス名にLSがあるので lsがついているのは冗長だと思います。
また、ここのメソッド名は printですが、FormatXXXの方は outputですが特に意図が無ければ合わせた方が良いと思います。

2023-12-22 15:38 UTC, u1tnk commented on 07.ls_object/lib/ls_command.rb
> +    @directory_with_format.output(terminal_width)
initializeで前処理して出力するだけというのは悪くは無いのですが、ここはメイン処理なので全体の処理の流れが分かるように書いてもらった方が嬉しいです。

2023-12-22 15:38 UTC, u1tnk commented on 07.ls_object/lib/directory.rb
> +  def initialize(path_names)
これだとほとんど配列と変わりません。
Directoryに任せられる責務は無いでしょうか？

2023-12-22 15:38 UTC, u1tnk commented on 07.ls_object/lib/file_info.rb
> +  def status
このstatusはあまり良くないですね。
理由はこのstatusを使う方がblockを欲しいとして、statusというメソッドで返ってきたhashのkey: blockに入っているというのがちょっと冗長かつ分かりづらいです。

blockというメソッドを使うと返ってくる方が分かりやすくないですか？
オブジェクト指向ではクラスを使う方は最低限の知識で使えるように、細かい事はクラス内部で隠して実装するというのが大事です。

2023-12-22 15:38 UTC, u1tnk commented on 07.ls_object/lib/file_info.rb
> +  FILE_TYPE = { 'file' => '-', 'directory' => 'd', 'link' => 'l', 'fifo' => 'p', 'characterSpecial' => 'c', 'blockSpecial' => 'b', 'socket' => 's' }.freeze
細かいテクニックの話ですが

```
FILE_TYPE = {
  'file' => '-', 
  'directory' => 'd',
...
```

と改行を入れておいた方が行数は増えますが見やすいですし、編集するときもやりやすいです。

2023-12-22 15:38 UTC, u1tnk commented on 07.ls_object/lib/file_info.rb
> +  def file_update_time
これも細かいネーミングの話ですが、 更新、作成時間だと `created_at`/`updated_at` の方が英語的に自然なようで、とてもよく見ます。

また、FileInfoクラスなので fileは無くて良いでしょう

2023-12-25 10:03 UTC, motohiro-mm reviewed
修正いたしました！
理解が不安なところはコメントに書かさせていただきましたので確認をお願いします。

2023-12-25 10:03 UTC, motohiro-mm commented on 07.ls_object/lib/ls_command.rb
> +    @directory_with_format = options['l'] ? FormatLong.new(pick_up_path_names(options, path)) : FormatShort.new(pick_up_path_names(options, path))
クラス名、自分では`Format`を名詞のつもりで使っていましたが、それなら`LongFormat`とすべきでした。そして`Formatter`のほうが「書式を変換するもの」という意味が伝わりやすいですね。
クラス名、変数名ともに修正しました。

2023-12-25 10:03 UTC, motohiro-mm commented on 07.ls_object/lib/directory.rb
> +  def initialize(path_names)
元々FormatLongクラスに入っていた`max_length_stat`メソッド等はDirectoryごとの最大を出すので、Directoryクラスにもたせるようにしました。

2023-12-25 10:03 UTC, motohiro-mm commented on 07.ls_object/lib/file_info.rb
> +  def status
最初１つのファイルごとにまとまっていたらわかりやすいのかと思い`status`メソッドを作成しましたが、後々にkeyで値を出して…とやっていくのが難しいなと自分でも悩んでいた部分でした。

> blockというメソッドを使うと返ってくる方が分かりやすくないですか？

単純にメソッド化してみたらそちらの方がかなり簡単で分かりやすくなりました！
ありがとうございます。

> 細かい事はクラス内部で隠して実装するというのが大事です。

と言う部分が、正直今もなんとなく理解がふわっとしてしまっています。すみません。
例えばどういった部分が細かい事に該当してきますか？今回修正した、`block`メソッドや`link`メソッド等でしょうか。

2023-12-25 10:03 UTC, motohiro-mm commented on 07.ls_object/lib/file_info.rb
> +  def file_update_time
修正しました！

2023-12-25 10:03 UTC, motohiro-mm commented on 07.ls_object/lib/ls_command.rb
> +  def ls_print(terminal_width)
outputに修正しました。

2023-12-25 10:03 UTC, motohiro-mm commented on 07.ls_object/lib/ls_command.rb
> +    @directory_with_format.output(terminal_width)
> initializeで前処理して出力するだけというのは悪くは無いのですが、ここはメイン処理なので全体の処理の流れが分かるように書いてもらった方が嬉しいです。

自分なりに全体の処理の流れを書くように修正したつもりなのですが、自信は正直ありません。
解釈違い等ありましたら再度ご指摘いただきたいです。

2023-12-25 10:03 UTC, motohiro-mm commented on 07.ls_object/lib/file_info.rb
> +  FILE_TYPE = { 'file' => '-', 'directory' => 'd', 'link' => 'l', 'fifo' => 'p', 'characterSpecial' => 'c', 'blockSpecial' => 'b', 'socket' => 's' }.freeze
たしかにそのほうがみやすいですね！
修正しました。

2023-12-27 16:34 UTC, u1tnk commented
> 例えばどういった部分が細かい事に該当してきますか？今回修正した、blockメソッドやlinkメソッド等でしょうか。

指摘した部分で言うと、 FileInfoクラスを使う側が blockを欲しいという状況だと、
-  FileStatなどを使って取得する処理内容
- 修正前の処理だとhash内のどのキーに入っているか

というのが細かいことです。

blockが欲しいときは blockを呼びだすだけで良いと使う側はラクになりますね。

2023-12-27 16:59 UTC, u1tnk commented on 07.ls_object/lib/directory.rb
> +  def sum_blocks
そうそう、複数のファイルが必要なものはここですね 👍

2023-12-27 16:59 UTC, u1tnk commented on 07.ls_object/lib/directory.rb
> +  def max_length_of_stat(files_status)
まず、これは引数のものをそのまま使うだけなので、まずインスタンスメソッドでは無いです。必要ならばクラスメソッドになります。
なのですが、 files_statusで渡されるものはDirectoryの他のメソッドから取得可能なので、引数で渡されていることがおかしいですね。
なので、対応としては それぞれのメソッドを作ってしまうか、symbolでキー名だけ引数でもらって、ここで `@files_info` から取得するのどちらかが良いと思います。

あと、メソッド名も良くないですね、 statから取るかどうかは使う方にはどうでも良い情報なのでその部分は不要と思います。

2023-12-27 16:59 UTC, u1tnk commented on 07.ls_object/lib/directory.rb
> +    @files_info = paths.map { |path| FileInfo.new(path) }
細かいので今回修正までする必要は無いですが、複数形で配列などを表現する慣習上infoのような複数系が無いのは困るのでその点でも避けた方が良い名前です。
filesの部分で表現してるとは思うのですが、例えば files_directories などという変数名があったとして 「ファイルの配列が入っているdirectoryの配列」という内容の二次元配列かな？と思ってしまうので、前半の複数形がどうなっているか迷ってしまいそうです。

2023-12-27 16:59 UTC, u1tnk commented on 07.ls_object/lib/long_formatter.rb
> +  def output(_)
この引数の `_` は何を意味していますでしょうか？

2023-12-27 16:59 UTC, u1tnk commented on 07.ls_object/lib/ls_command.rb
> +  def format
ここは何かの formatterを返すメソッドで format自体をするメソッドでは無いので `formatter`という名前の方が良いです。
`format.output` だとちょっとおかしいですしね。

2023-12-27 16:59 UTC, u1tnk commented on 07.ls_object/lib/ls_command.rb
> +  def format
output以外が外部から呼ばれないなら privateメソッドにするべきですね。全部チェックしていませんが、他のクラスも同様です。

2023-12-27 16:59 UTC, u1tnk commented on 07.ls_object/lib/ls_command.rb
> +    format.output(terminal_width)
流れがわかりやすいコードをざっくり疑似コード的に書くと

```
directory = get_directory
formatter = long_format? LongFormatter.new(directory) : ShortFormatter.new(directory)
formatter.output
```
というイメージでした。

とはいえ現状でもクラス内に書くやり方としては悪くないので、流れに関しては修正不要です！

2023-12-27 23:57 UTC, motohiro-mm commented on 07.ls_object/lib/directory.rb
> +  def max_length_of_stat(files_status)
> files_statusで渡されるものはDirectoryの他のメソッドから取得可能なので、引数で渡されていることがおかしいですね。

たしかにせっかくそれぞれメソッドを作ったのにうまく使えていないですね。
今回再度調べて`send`メソッドを初めて知ったので、シンボルのkeysを渡して最大値を取得する方法にしました。

あとで呼び出す時にわかりやすいかなと思いハッシュ化したのですが、普通に`max_lengths[1]`のような形で呼び出すほうが良かったでしょうか？

2023-12-27 23:57 UTC, motohiro-mm commented on 07.ls_object/lib/directory.rb
> +  def sum_blocks
認識が合っていて良かったです！ありがとうございます！

2023-12-27 23:57 UTC, motohiro-mm commented on 07.ls_object/lib/directory.rb
> +    @files_info = paths.map { |path| FileInfo.new(path) }
> 複数形で配列などを表現する慣習上infoのような複数系が無いのは困るのでその点でも避けた方が良い名前です。
filesの部分で表現してるとは思うのですが、例えば files_directories などという変数名があったとして 「ファイルの配列が入っているdirectoryの配列」という内容の二次元配列かな？と思ってしまうので、前半の複数形がどうなっているか迷ってしまいそうです。

自分でも悩んでた部分でした。
例えばFileStatisticクラスにすれば複数にできるかなと思ったのですが、statisticが統計なのでそれに名前とかを含んでいいのかと考えたりして結局FileInfoクラスにしていました。
なにか良い名前があったらヒントをいただきたいです。

2023-12-27 23:57 UTC, motohiro-mm commented on 07.ls_object/lib/long_formatter.rb
> +  def output(_)
ShortFormatterクラスの`output`で引数に`terminal_width`が必要なのでLsCommandクラスの`output`メソッドで引数に`terminal_width`をとるようにしています。LongFormatterクラスの`output`メソッドは引数を必要としていないので、この引数はメソッドの中で使ってないということを表す意味で`_`にしました。

2023-12-27 23:57 UTC, motohiro-mm commented on 07.ls_object/lib/ls_command.rb
> +    format.output(terminal_width)
なるほど！たしかに上記のコードの方が流れが明らかで分かりやすいですね！

修正不要とのことなのでそのままにしましたが、今後は全体の流れをもっと分かりやすくなるように意識していきます。

2023-12-27 23:57 UTC, motohiro-mm commented on 07.ls_object/lib/ls_command.rb
> +  def format
> ここは何かの formatterを返すメソッドで format自体をするメソッドでは無い

たしかにそうですね。修正しました。
privateメソッドにも修正しました。

2023-12-28 00:07 UTC, motohiro-mm commented
> オブジェクト指向ではクラスを使う方は最低限の知識で使えるように、細かい事はクラス内部で隠して実装するというのが大事です。

>指摘した部分で言うと、 FileInfoクラスを使う側が blockを欲しいという状況だと、
FileStatなどを使って取得する処理内容
修正前の処理だとhash内のどのキーに入っているか
というのが細かいことです。
blockが欲しいときは blockを呼びだすだけで良いと使う側はラクになりますね。

なるほど！blockが欲しい時はblockメソッドを呼び出すだけで、その中身（どうやって取得するかやhashのどのキーか等）は外からは分からずに隠されている方が良いということですね。これがクラスの役割の１つの「隠す」にあたるわけですね。
よく分かりました！ありがとうございます。

修正しましたので、確認をお願いします！

2023-12-28 06:16 UTC, u1tnk commented on 07.ls_object/lib/directory.rb
> +    @files_info = paths.map { |path| FileInfo.new(path) }
> なにか良い名前があったらヒントをいただきたいです。

難しいところですねー
よくあるのが lsモジュールを作って Ls::File、もしくは LsFile。
Infoの言い替えだとFileDetailとかでしょうか。

あと、オススメするわけでは無く参考情報ですが、`file_infos` みたいに英語に無い仮複数形も見ることはあります。あんまり良くないですが、意図は伝わるという。

2023-12-28 06:24 UTC, u1tnk commented on 07.ls_object/lib/directory.rb
> +  def max_length_of_stat(files_status)
現状変更されていないようですが push忘れとかでしょうか？

> 今回再度調べてsendメソッドを初めて知ったので、シンボルのkeysを渡して最大値を取得する方法にしました。

sendはsecurityなどの問題で要注意です。外部からの文字列でsendするなどはNGですね。
まあ自分で呼ぶだけなら許容範囲かなと思いますが、メンターで意見が分かれそうなところなのは留意ください。
あと、sendではなく public_send の方がprivateメソッドが呼べないので多少安全で良いですね。

>あとで呼び出す時にわかりやすいかなと思いハッシュ化したのですが、外から呼び出す際にハッシュのキーを考えなければならないことを考えるとこちらもあまり良くないでしょうか？普通にmax_lengths[1]のような形で呼び出すほうが良かったでしょうか？

ちょっと現状のコードが分からないので判断難しいですが、配列の添字よりはハッシュのキーの方が分かりやすいと思います。

2023-12-28 06:24 UTC, u1tnk commented on 07.ls_object/lib/long_formatter.rb
> +  def output(_)
あー、なるほど。
インタフェースを合わせたわけですね。
そうであれば、ShortFormatter のinitializeはコードが別なのでそこで terminal_widthを渡して、outputでは引数が無い方が良いかと思います。

2023-12-28 11:12 UTC, motohiro-mm reviewed
大変失礼しました。
コメントいただいた部分も含め再度修正しpushしています。
ご確認をよろしくお願いします。

2023-12-28 11:12 UTC, motohiro-mm commented on 07.ls_object/lib/long_formatter.rb
> +  def output(_)
> そうであれば、ShortFormatter のinitializeはコードが別なのでそこで terminal_widthを渡して、outputでは引数が無い方が良いかと思います。

なるほど、たしかにわざわざ`output`で渡さなくても`new`するときに渡せばLongFormatterクラスには渡さずにすみますね。
修正しました！

2023-12-28 11:12 UTC, motohiro-mm commented on 07.ls_object/lib/directory.rb
> +    @files_info = paths.map { |path| FileInfo.new(path) }
detail（詳細）良いですね！
そちらに修正しました！ありがとうございます。

2023-12-28 11:12 UTC, motohiro-mm commented on 07.ls_object/lib/directory.rb
> +  def max_length_of_stat(files_status)
大変失礼しました。pushし忘れていたようです。すみませんでした。

> sendはsecurityなどの問題で要注意です。外部からの文字列でsendするなどはNGですね。
まあ自分で呼ぶだけなら許容範囲かなと思いますが、メンターで意見が分かれそうなところなのは留意ください。
あと、sendではなく public_send の方がprivateメソッドが呼べないので多少安全で良いですね。

調べた際も外部からの入力をsendするのは絶対ダメとあり、今回は自分の中だけなので良いのかと思っていましたが、メンターさんの中でも意見が割れそうな部分なのですね。承知しました。
今回私が書いたコードだと、`links`メソッドや`user_names`メソッドなど全てprivateのメソッドにしていたので`public_send`は使うことができませんでした。
そうなってくると、安全性の面で考えたらそれぞれにメソッド定義して最大を求める形にした方がよいのでしょうか。それとも`send`を使う以外で他の書き方があるのでしょうか。

2023-12-28 15:29 UTC, u1tnk approved these changes
> 今回私が書いたコードだと、linksメソッドやuser_namesメソッドなど全てprivateのメソッドにしていたのでpublic_sendは使うことができませんでした。


そうか、今回は自分のメソッドだけを呼んでいるからprivate methodを呼ぶ必要がありますね。確かに send で良いと思います。

> そうなってくると、安全性の面で考えたらそれぞれにメソッド定義して最大を求める形にした方がよいのでしょうか。それともsendを使う以外で他の書き方があるのでしょうか。

単純に case文などを使って愚直にやるあたりでしょうか。


```
case key 
when :links
  links
when xxx
  .....
end
```

あとは外部からの呼び出しでは無いですし、冗長ですがfile_detailsの方を対象にキー名でデータを取得するとかですね。

個人的には微妙なライン(sendの方が大幅に読みやすくなるならアリ) なので このままでも大丈夫です！ 

ちなみに、まだ挙がってないデメリットとしては 「メソッドを呼び出している
部分を全部修正したいときなどにgrepしても見つらなくなる」というのもありますね。

ここらへんはプロジェクトのポリシーもしくは過去コードとの兼ねあいで決まる感じですね。
微妙なんだなということだけ留意しておいてください。

2023-12-29 03:09 UTC, motohiro-mm commented
case文！なるほど〜思いつきませんでした。それならそれぞれのメソッドを実行できますね。

> あとは外部からの呼び出しでは無いですし、冗長ですがfile_detailsの方を対象にキー名でデータを取得するとかですね。

directoryのほうではなくその中のfile_detailsにアプローチするということですね。そちらなら`public_send`でできそうです。
色々な方法を提示していただいて勉強になりました！
`send`メソッドは使い方が難しく要注意ということは覚えておきます！

丁寧にご指導していただきありがとうございました！

2023-12-29 03:09 UTC, merged