Add bowling.rb
motohiro-mm/ruby-practices pull request #5
Opened 2022-12-07 04:59 UTC by motohiro-mm

2022-12-12 14:59 UTC, u1tnk commented on 03.bowling/bowling.rb
> +shots.each_slice(2) do |s|
`frames = shots.each_slice(2).to_a`と同じだと思います。

2022-12-12 14:59 UTC, u1tnk commented on 03.bowling/bowling.rb
> +  frame.pop if frame == [10, 0]
そのままにするならともかく0を再度消すのであればeach_sliceを使わず、最初の `scores.each`のところでロジックで分割してあげれば良いと思います。
既に10フレームはロジック足して分割しているわけですし。

2022-12-13 12:29 UTC, motohiro-mm commented on 03.bowling/bowling.rb
> +shots.each_slice(2) do |s|
昨日勉強していて`to_a`を知りました！勉強になります！

2022-12-13 12:33 UTC, motohiro-mm commented on 03.bowling/bowling.rb
> +  frame.pop if frame == [10, 0]
`each_slice`を使わない方法へ、framesへの条件分岐を変更しました。

2022-12-13 12:35 UTC, motohiro-mm commented
フレームへの条件分岐を修正致しました。ご確認のほどよろしくお願いいたします。

2022-12-13 15:01 UTC, u1tnk requested changes
大体良いのですが、良くなった結果細かいところが気になったのでもうちょっと改善してみてください 🙏

2022-12-13 15:01 UTC, u1tnk commented on 03.bowling/bowling.rb
> +frames.delete([])
こまかいですが、一回追加して後で消すのは綺麗では無いので、 `one_frame = []` のところで最後のframeだったら追加しないようにしましょう。
ヒントとして each_with_indexなど使うと簡単じゃないかと思います。

2022-12-13 15:01 UTC, u1tnk commented on 03.bowling/bowling.rb
> +    one_frame << 10
細かいですが、 `one_frame`は一つのframeという意味かと思いますが、 last_frameがあるので frameだけだと気持ち悪いのは分かるのですが、 last_frameがあるので逆に 最初の一つかな？と思ってしまいましたのでより良い名前を考えてみてください。

ちょっと難しいと思うので案だけ出しますね。僕がつけるとしたら `current_frame`、`temp_frame`あたりでしょうか。

2022-12-13 15:01 UTC, u1tnk commented on 03.bowling/bowling.rb
> +result = [numbers, frames].transpose.to_h
ちょっと複雑ですね。frameの番号が欲しいのであれば 前述した `frame_with_index`で使えば良いかなと思います。

2022-12-14 04:43 UTC, motohiro-mm commented on 03.bowling/bowling.rb
> +    one_frame << 10
点数計算のほうで`frame`を使っていたので`one_frame`としていました。`current_frame`分かりやすいのでそちらに修正させていただきます！

2022-12-14 12:25 UTC, motohiro-mm commented on 03.bowling/bowling.rb
> +    one_frame << 10
すいません、修正していくうちに`last_frame`がなくなったので、全て`frame`で書きました。よろしくお願いいたします。

2022-12-14 12:26 UTC, motohiro-mm commented on 03.bowling/bowling.rb
> +frames.delete([])
`each_with_index`を使って修正いたしました。

2022-12-14 12:28 UTC, motohiro-mm commented on 03.bowling/bowling.rb
> +result = [numbers, frames].transpose.to_h
`each_with_index`を使うコードに修正いたしました。

2022-12-14 12:29 UTC, motohiro-mm commented
修正いたしましたので、ご確認のほどよろしくお願いいたします。

2022-12-14 15:01 UTC, u1tnk approved these changes
コメントしてますが、だいぶ細かいのでapproveします！
だいぶスッキリしましたね 👍

2022-12-14 15:01 UTC, u1tnk commented on 03.bowling/bowling.rb
> +scores.map! { |s| s == 'X' ? '10' : s }.map!(&:to_i)
これに気づいたので十分偉いんですが、  `{ |s| s == 'X' ? 10 : s.to_i }`にすれば`map!`は一個で済むと思います。

2022-12-15 11:28 UTC, motohiro-mm commented on 03.bowling/bowling.rb
> +scores.map! { |s| s == 'X' ? '10' : s }.map!(&:to_i)
そうなのですね！自分で短く書くやり方を考えたのですがうまくできなかったので、勉強になります！ありがとうございます！

2022-12-15 11:33 UTC, merged